version = 1
gitignore = true
# Keeps all the skills up to date
pin = false
agents = ["claude", "cursor"]

[trust]
allow_all = true

[[skills]]
name = "*"
source = "getsentry/skills"

[[skills]]
name = "warden-sweep"
source = "getsentry/warden"

[[skills]]
name = "warden"
source = "getsentry/warden"
